spring:
  application:
    name: pesonaflower
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pesona_flower
    username: postgres
    password: 123


