spring:
  security:
    user:
      password: test
      name: test
  application:
    name: pesonaflower
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pesona_flower
    username: postgres
    password: 123
  thymeleaf:
    suffix: .html



