spring:
  security:
    user:
      password: test
      name: test
  application:
    name: pesonaflower
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pesona_flower
    username: postgres
    password: 123
  thymeleaf:
    suffix: .html
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  error:
    whitelabel:
      enabled: false



